### ISSUE TITLE
Calendar approach

### ISSUE THREAD

**Issue by BarTracz** [blumilksoftware/heatmap#11]
Change the design to resemble a calendar

**Comment by krzysztofrewak** [comment]
Current approach should stay here as an option (or even default option). Please reconsider this task as a "add a new way to present data".

**Comment by BarTracz** [comment]
After thinking for some time i`ve come to a conclusion that it is up to user how to present data, so we should provide only tools for building heatmap, and user should configure it as he likes. And everything should be explained in #3
