### ISSUE TITLE
Timezone handling

### ISSUE THREAD

**Issue by krzysztofrewak** [blumilksoftware/heatmap#7]
I believe that there would be multiple problems with timezones within this package. It should be studied, discussed and refactored to handle timezones of provided data.

Bonus: probably we should update package to Carbon 3.

**Comment by BarTracz** [comment]
I will probably need to refactor HeatmapBuilder, because seems like it does not carre for hours making implementing time zones impossible. But i don`t know yet what is responsible for ignoring everything except date. Maybe it is Carbon thing.

**Comment by krzysztofrewak** [comment]
Please don't rewrite anything without consulations. I think this can be managed on Carbon-level only.

**Comment by BarTracz** [comment]
I tried to make heatmap with time zones for hours only and it works, so i guess Carbon cuts hour part out of date, so i will have to change just that to make this work hopefully.

**Comment by BarTracz** [comment]
Nevermind, it works fine now.
